name: "Check Deprecations"

on:
  pull_request:
    # Runs on PRs to main
    branches:
      - main

jobs:
  deprecations-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: ./.go-version
          cache: true
      - name: Install required tools
        run: |
          make bootstrap
      - name: Check deprecations for files in diff
        run: |
          # Need to run this from repository root and not from scripts/ as staticcheck works 
          # only on packages
          ./scripts/deprecations-checker.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.repository.name }}
          