name: Check Go Docs for tests

on:
  pull_request:
    types: [opened, synchronize]
    # Runs on PRs to main
    branches:
      - main

jobs:
  godoc-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Set Up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          cache: true
          go-version-file: ./.go-version
      - name: Verify new tests have go docs
        run: make ci-vet-godoctests
